local opts = {
  attach_mode = "global",
  backends = { "lsp", "treesitter", "markdown", "man" },
  layout = { default_direction = "prefer_right" },
  ignore = { filetypes = { "NvimTree", "terminal", "nofile" } },
  manage_folds = "auto",
  keymaps = {
    ["?"] = "actions.show_help",
    ["g?"] = "actions.show_help",
    ["<CR>"] = "actions.jump",
    ["<2-LeftMouse>"] = "actions.jump",
    ["<C-v>"] = "actions.jump_vsplit",
    ["<C-s>"] = "actions.jump_split",
    ["<C-d>"] = "actions.down_and_scroll",
    ["<C-u>"] = "actions.up_and_scroll",
    ["{"] = "actions.prev",
    ["}"] = "actions.next",
    ["[["] = "actions.prev_up",
    ["]]"] = "actions.next_up",
    ["q"] = "actions.close",
    ["o"] = "actions.tree_toggle",
    ["O"] = "actions.tree_toggle_recursive",
    ["zr"] = "actions.tree_increase_fold_level",
    ["zR"] = "actions.tree_open_all",
    ["zm"] = "actions.tree_decrease_fold_level",
    ["zM"] = "actions.tree_close_all",
    ["zx"] = "actions.tree_sync_folds",
    ["zX"] = "actions.tree_sync_folds",
  },
  filter_kind = {
    "Array",
    "Boolean",
    "Class",
    "Constant",
    "Constructor",
    "Enum",
    "EnumMember",
    "Event",
    "Field",
    "File",
    "Function",
    "Interface",
    "Key",
    "Method",
    "Module",
    "Namespace",
    "Null",
    -- "Number",
    "Object",
    "Operator",
    "Package",
    -- "Property",
    -- "String",
    "Struct",
    -- "TypeParameter",
    -- "Variable",
  },
  close_on_select = true,
  highlight_on_jump = false,
  disable_max_lines = 20000,
  disable_max_size = 1000000,
}

return opts
